Summary:     K Desktop Environment - Graphic Applications
Summary(pl): K Desktop Environment - Aplikacje graficzne
Name:        kdegraphics
Version:     1.0
Release:     7
Source:      ftp://ftp.kde.org/pub/kde/stable/%{version}/distribution/tar/generic/source/%{name}-%{version}.tar.gz
Group:       X11/KDE/Graphics
Copyright:   GPL
Requires:    qt >= 1.40, kdelibs = %{version}
Vendor:      The KDE Team
BuildRoot:   /tmp/%{name}-%{version}-root

%description
Graphic applications for the K Desktop Environment.

Included with this package are:

KDVI: displays TeX's device independent (.dvi) files
KFax: displays fax files
KFract: a fractal generator
KGhostview: displays postscript (.ps) files
KPaint: a simple drawing program
KView: displays numerous graphic file formats 

%description -l pl
Aplikacje graficzne dla KDE.
Pakiet zawiera:
  KDVI - Przegl±darka plików DVI
  KFax - Program do wy¶wietlania faksów
  KFract - Generator fraktali4yy
  KGhostview - Program do ogl±dania postscriptu (.ps)
  KPaint - Prosty program do grafiki rastrowej
  KView - Przegl±darka plików graficznych

%package -n kdvi
Summary:     KDE DVI viewer
Summary(pl): Przegl±darka plików DVI dla KDE
Group:       X11/KDE/Graphics
Requires:    qt >= 1.40, kdelibs = %{version}

%description -n kdvi
A tool for viewing DVI files generated by TeX system.

%description -l pl -n kdvi
Program do przegl±dania plików DVI.

%package -n kfax
Summary:     KDE Fax viewer	
Summary(pl): Przegl±darka faksów dla KDE
Group:       X11/KDE/Graphics
Requires:    qt >= 1.40, kdelibs = %{version}

%description -n kfax
A Fax viewer for KDE.

%description -l pl -n kfax
Program ten umo¿liwia przegl±danie plików faksowych (G3)

%package -n kfract
Summary:     KDE fractal generator	
Summary(pl): Generator fraktali dla KDE
Group:       X11/KDE/Graphics
Requires:    qt >= 1.40, kdelibs = %{version}

%description -n kfract
A Fractal generator for KDE.

%description -l pl -n kfract
Generator fraktali dla KDE

%package -n kghostview 
Summary:     KDE Postscript viewer
Summary(pl): Przegl±darka postscriptu dla KDE
Group:       X11/KDE/Graphics
Requires:    qt >= 1.40, kdelibs = %{version}

%description -n kghostview
Postscript files (.ps) viewer for KDE

%description -l pl -n kghostview
Program ten umo¿liwia przegl±danie plików postscriptowych (.ps) 

%package -n kpaint
Summary:     KDE Painter
Summary(pl): Program graficzny KDE
Group:       X11/KDE/Graphics
Requires:    qt >= 1.40, kdelibs = %{version}

%description -n kpaint
A (very) simple painting program for KDE.

%description -l pl -n kpaint
(Bardzo) prosty program do rysowania pod KDE.

%package -n kview
Summary:     KDE graphics file viewer
Summary(pl): Przegl±darka plików graficznych dla KDE
Group:       X11/KDE/Graphics
Requires:    qt >= 1.40, kdelibs = %{version}

%description -n kview
A graphics files viewer for KDE.

%description -l pl -n kfax
Program ten umo¿liwia ogl±danie ró¿nych plików graficznych (G3)

%prep
%setup -q

%build
export KDEDIR=/usr/X11R6
CXXFLAGS="$RPM_OPT_FLAGS -Wall" CFLAGS="$RPM_OPT_FLAGS -Wall" \
./configure %{_target} \
	--prefix=$KDEDIR \
 	--with-install-root=$RPM_BUILD_ROOT \
 	--with-pam="yes"
make KDEDIR=$KDEDIR

%install
rm -rf $RPM_BUILD_ROOT
export KDEDIR=/usr/X11R6
make RUN_KAPPFINDER=no prefix=$RPM_BUILD_ROOT$KDEDIR install

# create wmconfig files
install -d $RPM_BUILD_ROOT/etc/X11/wmconfig
DIR=$PWD
cd $RPM_BUILD_ROOT/etc/X11/kde/applnk
for kdelnk in `find . -name "*.kdelnk"` ; do
  PKG=kde`basename $kdelnk|sed -e "s/\.kdelnk$//"`;
  SECT=`dirname $kdelnk|sed -e "s/^\.\/*//"`;
  kdelnk2wmconfig $PKG $kdelnk $RPM_BUILD_ROOT/etc/X11/wmconfig/$PKG KDE/$SECT pl
done
cd $DIR

%clean
rm -rf $RPM_BUILD_ROOT

#################################################
#             KDVI
#################################################

%files -n kdvi
%defattr(644,root,root,755)
%config(missingok) /etc/X11/kde/applnk/Graphics/kdvi.kdelnk
%config(missingok) /etc/X11/wmconfig/kdekdvi
%attr(755,root,root) /usr/X11R6/bin/kdvi
%lang(en) /usr/X11R6/share/kde/doc/HTML/en/kdvi
%lang(fi) /usr/X11R6/share/kde/doc/HTML/fi/kdvi
/usr/X11R6/share/kde/apps/kdvi/
/usr/X11R6/share/kde/icons/kdvi.xpm
/usr/X11R6/share/kde/icons/mini/kdvi.xpm
%lang(cs) /usr/X11R6/share/locale/cs/LC_MESSAGES/kdvi.mo
%lang(de) /usr/X11R6/share/locale/de/LC_MESSAGES/kdvi.mo
%lang(el) /usr/X11R6/share/locale/el/LC_MESSAGES/kdvi.mo
%lang(es) /usr/X11R6/share/locale/es/LC_MESSAGES/kdvi.mo
%lang(fi) /usr/X11R6/share/locale/fi/LC_MESSAGES/kdvi.mo
%lang(fr) /usr/X11R6/share/locale/fr/LC_MESSAGES/kdvi.mo
%lang(hr) /usr/X11R6/share/locale/hr/LC_MESSAGES/kdvi.mo
%lang(hu) /usr/X11R6/share/locale/hu/LC_MESSAGES/kdvi.mo
%lang(it) /usr/X11R6/share/locale/it/LC_MESSAGES/kdvi.mo
%lang(nl) /usr/X11R6/share/locale/nl/LC_MESSAGES/kdvi.mo
%lang(no) /usr/X11R6/share/locale/no/LC_MESSAGES/kdvi.mo
%lang(pl) /usr/X11R6/share/locale/pl/LC_MESSAGES/kdvi.mo
%lang(pt) /usr/X11R6/share/locale/pt/LC_MESSAGES/kdvi.mo
%lang(pt) /usr/X11R6/share/locale/pt_*/LC_MESSAGES/kdvi.mo
%lang(sk) /usr/X11R6/share/locale/sk/LC_MESSAGES/kdvi.mo
%lang(zh) /usr/X11R6/share/locale/zh_*/LC_MESSAGES/kdvi.mo

#################################################
#             KFAX
#################################################

%files -n kfax
%defattr(644,root,root,755)
%config(missingok) /etc/X11/kde/applnk/Graphics/KFax.kdelnk
%config(missingok) /etc/X11/wmconfig/kdeKFax
%attr(755,root,root) /usr/X11R6/bin/kfax
%lang(en) /usr/X11R6/share/kde/doc/HTML/en/kfax
/usr/X11R6/share/kde/apps/kfax/
/usr/X11R6/share/kde/icons/mini/kfax.xpm
/usr/X11R6/share/kde/icons/kfax.xpm
%lang(cs) /usr/X11R6/share/locale/cs/LC_MESSAGES/kfax.mo
%lang(de) /usr/X11R6/share/locale/de/LC_MESSAGES/kfax.mo
%lang(es) /usr/X11R6/share/locale/es/LC_MESSAGES/kfax.mo
%lang(fi) /usr/X11R6/share/locale/fi/LC_MESSAGES/kfax.mo
%lang(hr) /usr/X11R6/share/locale/hr/LC_MESSAGES/kfax.mo
%lang(no) /usr/X11R6/share/locale/no/LC_MESSAGES/kfax.mo
%lang(pl) /usr/X11R6/share/locale/pl/LC_MESSAGES/kfax.mo
%lang(pt) /usr/X11R6/share/locale/pt*/LC_MESSAGES/kfax.mo
%lang(sk) /usr/X11R6/share/locale/sk/LC_MESSAGES/kfax.mo
%lang(zh) /usr/X11R6/share/locale/zh*/LC_MESSAGES/kfax.mo

#################################################
#             KFract
#################################################

%files -n kfract
%defattr(644,root,root,755)
%config(missingok) /etc/X11/kde/applnk/Graphics/kfract.kdelnk
%config(missingok) /etc/X11/wmconfig/kdekfract
%attr(755,root,root) /usr/X11R6/bin/kfract
%lang(en) /usr/X11R6/share/kde/doc/HTML/en/kfract
/usr/X11R6/share/kde/icons/mini/kfract.xpm
/usr/X11R6/share/kde/icons/kfract.xpm

#################################################
#             KGHOSTVIEW
#################################################

%files -n kghostview
%defattr(644,root,root,755)
%config(missingok) /etc/X11/kde/applnk/Graphics/kghostview.kdelnk
%config(missingok) /etc/X11/wmconfig/kdekghostview
%attr(755,root,root) /usr/X11R6/bin/kghostview
%lang(en) /usr/X11R6/share/kde/doc/HTML/en/kghostview
/usr/X11R6/share/kde/icons/mini/kghostview.xpm
/usr/X11R6/share/kde/icons/kghostview.xpm
%lang(cs) /usr/X11R6/share/locale/cs/LC_MESSAGES/kghostview.mo
%lang(de) /usr/X11R6/share/locale/de/LC_MESSAGES/kghostview.mo
%lang(el) /usr/X11R6/share/locale/el/LC_MESSAGES/kghostview.mo
%lang(es) /usr/X11R6/share/locale/es/LC_MESSAGES/kghostview.mo
%lang(fi) /usr/X11R6/share/locale/fi/LC_MESSAGES/kghostview.mo
%lang(fr) /usr/X11R6/share/locale/fr/LC_MESSAGES/kghostview.mo
%lang(hr) /usr/X11R6/share/locale/hr/LC_MESSAGES/kghostview.mo
%lang(hu) /usr/X11R6/share/locale/hu/LC_MESSAGES/kghostview.mo
%lang(it) /usr/X11R6/share/locale/it/LC_MESSAGES/kghostview.mo
%lang(mk) /usr/X11R6/share/locale/mk/LC_MESSAGES/kghostview.mo
%lang(nl) /usr/X11R6/share/locale/nl/LC_MESSAGES/kghostview.mo
%lang(no) /usr/X11R6/share/locale/no/LC_MESSAGES/kghostview.mo
%lang(pl) /usr/X11R6/share/locale/pl/LC_MESSAGES/kghostview.mo
%lang(pt) /usr/X11R6/share/locale/pt*/LC_MESSAGES/kghostview.mo
%lang(ru) /usr/X11R6/share/locale/ru/LC_MESSAGES/kghostview.mo
%lang(sk) /usr/X11R6/share/locale/sk/LC_MESSAGES/kghostview.mo
%lang(sv) /usr/X11R6/share/locale/sv/LC_MESSAGES/kghostview.mo
%lang(zh) /usr/X11R6/share/locale/zh*/LC_MESSAGES/kghostview.mo

#################################################
#             KPAINT
#################################################

%files -n kpaint
%defattr(644,root,root,755)
%config(missingok) /etc/X11/kde/applnk/Graphics/kpaint.kdelnk
%config(missingok) /etc/X11/wmconfig/kdekpaint
%attr(755,root,root) /usr/X11R6/bin/kpaint
%lang(en) /usr/X11R6/share/kde/doc/HTML/en/kpaint
/usr/X11R6/share/kde/apps/kpaint
/usr/X11R6/share/kde/icons/mini/kpaint.xpm
/usr/X11R6/share/kde/icons/kpaint.xpm
%lang(cs) /usr/X11R6/share/locale/cs/LC_MESSAGES/kpaint.mo
%lang(de) /usr/X11R6/share/locale/de/LC_MESSAGES/kpaint.mo
%lang(el) /usr/X11R6/share/locale/el/LC_MESSAGES/kpaint.mo
%lang(es) /usr/X11R6/share/locale/es/LC_MESSAGES/kpaint.mo
%lang(fi) /usr/X11R6/share/locale/fi/LC_MESSAGES/kpaint.mo
%lang(fr) /usr/X11R6/share/locale/fr/LC_MESSAGES/kpaint.mo
%lang(hr) /usr/X11R6/share/locale/hr/LC_MESSAGES/kpaint.mo
%lang(hu) /usr/X11R6/share/locale/hu/LC_MESSAGES/kpaint.mo
%lang(it) /usr/X11R6/share/locale/it/LC_MESSAGES/kpaint.mo
%lang(nl) /usr/X11R6/share/locale/nl/LC_MESSAGES/kpaint.mo
%lang(no) /usr/X11R6/share/locale/no/LC_MESSAGES/kpaint.mo
%lang(pl) /usr/X11R6/share/locale/pl/LC_MESSAGES/kpaint.mo
%lang(pt) /usr/X11R6/share/locale/pt*/LC_MESSAGES/kpaint.mo
%lang(ru) /usr/X11R6/share/locale/ru/LC_MESSAGES/kpaint.mo
%lang(sk) /usr/X11R6/share/locale/sk/LC_MESSAGES/kpaint.mo
%lang(sv) /usr/X11R6/share/locale/sv/LC_MESSAGES/kpaint.mo
%lang(zh) /usr/X11R6/share/locale/zh*/LC_MESSAGES/kpaint.mo

#################################################
#             KVIEW
#################################################

%files -n kview
%defattr(644,root,root,755)
%config(missingok) /etc/X11/kde/applnk/Graphics/kview.kdelnk
%config(missingok) /etc/X11/wmconfig/kdekview
%attr(755,root,root) /usr/X11R6/bin/kview
%lang(en) /usr/X11R6/share/kde/doc/HTML/en/kview
/usr/X11R6/share/kde/apps/kview/
/usr/X11R6/share/kde/icons/mini/kview.xpm
/usr/X11R6/share/kde/icons/kview.xpm

%changelog
* Wed Dec  8 1998 Tomasz K³oczko <kloczek@rudy.mif.pg.gda.pl>
  [1.0-7]
- recompiled against libstdc++.so.2.9.

* Sat Oct 24 1998 Jacek Konieczny <jajcus@zeus.polsl.gliwice.pl>
  [1.0-4]
- created new spec based on kdebase.spec
