Summary:	K Desktop Environment - Graphic Applications
Summary(pl):	K Desktop Environment - Aplikacje graficzne
Name:		kdegraphics
Version:	2.2.1
Release:	1
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
License:	GPL
Source0:	ftp://ftp.kde.org/pub/kde/stable/2.2.1/src/%{name}-%{version}.tar.bz2
BuildRequires:	kdelibs-devel >= 2.1
BuildRequires:	qt-devel >= 2.2
BuildRequires:	XFree86-devel >= 3.3.6
BuildRequires:	libstdc++-devel
BuildRequires:	libtiff-devel
BuildRequires:	libjpeg-devel
BuildRequires:	libungif-devel
BuildRequires:	libpng-devel >= 1.0.8
BuildRequires:	zlib-devel
BuildRequires:	sane-backends-devel
BuildRequires:	gettext-devel
BuildRequires:	libxml2-devel
Requires:	qt >= 2.2
Requires:	kdelibs = %{version}
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define 	_prefix		/usr/X11R6
%define		_htmldir	%{_datadir}/doc/kde/HTML

%description
Graphic applications for the K Desktop Environment.

Included with this package are:

KDVI: displays TeX's device independent (.dvi) files
KFax: displays fax files
KFract: a fractal generator
KGhostview: displays postscript (.ps) files
KIconedit: icon editor
KPaint: a simple drawing program
KSnapshot: screen capture
KView: displays numerous graphic file formats 

%description -l pl
Aplikacje graficzne dla KDE.
Pakiet zawiera:
  KDVI - Przegl±darka plików DVI
  KFax - Program do wy¶wietlania faksów
  KFract - Generator fraktali
  KGhostview - Program do ogl±dania postscriptu (.ps)
  KIconedit - Program do edycji ikon dla KDE
  KPaint - Prosty program do grafiki rastrowej
  KSnapshot - program do przechwytywania wygl±du ekranu
  KView - Przegl±darka plików graficznych


%package devel
Summary:	kdegraphics development files
Group:		X11/KDE/Development
Group(de):	X11/KDE/Entwicklung
Group(pl):	X11/KDE/Programowanie

%description devel
kdegraphics development files


%package kdvi
Summary:	KDE DVI viewer
Summary(pl):	Przegl±darka plików DVI dla KDE
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	qt >= 2.2
Requires:	kdelibs = %{version}

%description kdvi
A tool for viewing DVI files generated by TeX system.

%description -l pl kdvi
Program do przegl±dania plików DVI.


%package kfax
Summary:	KDE Fax viewer	
Summary(pl):	Przegl±darka faksów dla KDE
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	qt >= 2.2
Requires:	kdelibs = %{version}

%description kfax
A Fax viewer for KDE.

%description -l pl kfax
Program ten umo¿liwia przegl±danie plików faksowych (G3)


%package kfract
Summary:	KDE fractal generator	
Summary(pl):	Generator fraktali dla KDE
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	qt >= 2.2
Requires:	kdelibs = %{version}

%description kfract
A Fractal generator for KDE.

%description -l pl kfract
Generator fraktali dla KDE


%package kghostview 
Summary:	KDE Postscript viewer
Summary(pl):	Przegl±darka postscriptu dla KDE
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	qt >= 2.2
Requires:	kdelibs = %{version}

%description kghostview
Postscript files (.ps) viewer for KDE

%description -l pl kghostview
Program ten umo¿liwia przegl±danie plików postscriptowych (.ps) 


%package kiconedit
Summary:	KDE Icon Editor
Summary(pl):	Edytor ikon w ¶rodowisku KDE
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	qt >= 2.2
Requires:	kdelibs = %{version}

%description kiconedit
KDE Icon editor.

%description -l pl kiconedit
Edytor ikon dla KDE.


%package kpaint
Summary:	KDE Painter
Summary(pl):	Program graficzny KDE
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	qt >= 2.2
Requires:	kdelibs = %{version}

%description kpaint
A (very) simple painting program for KDE.

%description -l pl kpaint
(Bardzo) prosty program do rysowania pod KDE.


%package kruler
Summary:	KRuler
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	qt >= 2.2
Requires:	kdelibs = %{version}

%description kruler
KRuler is a very simple application, with only one aim in life.
To measure distances on your screen.


%package ksnapshot
Summary:	KDE Snap Shot
Summary(pl):	Program do przechwytywania ekranu dla KDE
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	qt >= 2.2
Requires:	kdelibs = %{version}

%description ksnapshot
Snapshot program for KDE.

%description -l pl ksnapshot
Program do przechwytywania ekranu dla KDE.


%package kview
Summary:	KDE graphics file viewer
Summary(pl):	Przegl±darka plików graficznych dla KDE
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	qt >= 2.2
Requires:	kdelibs = %{version}

%description kview
A graphics files viewer for KDE.

%description -l pl kfax
Program ten umo¿liwia ogl±danie ró¿nych plików graficznych (G3).


%package kooka
Summary:	Scanning tool
Summary(pl):	Narzêdzie do skanowania
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	kdelibs = %{version}

%description kooka
Scanning tool

%description -l pl kooka
Narzêdzie do skanowania


%package kcoloredit
Summary:	Color palette editor
Summary(pl):	Edytor palety kolorów
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	kdelibs = %{version}

%description kcoloredit
Color palette editor

%description -l pl kcoloredit
Edytor palety kolorów


%package kcolorchooser
Summary:	Color chooser
Summary(pl):	Wybieracz kolrów
Group:		X11/KDE/Graphics
Group(pl):	X11/KDE/Grafika
Requires:	kdelibs = %{version}

%description kcolorchooser
Color chooser

%description -l pl kcolorchooser
Wybieracz kolorów

%prep
%setup -q

%build
kde_htmldir="%{_htmldir}"; export kde_htmldir
kde_icondir="%{_pixmapsdir}"; export kde_icondir

%configure2_13 \
	--enable-final
%{__make}

%install
rm -rf $RPM_BUILD_ROOT
%{__make} RUN_KAPPFINDER=no DESTDIR=$RPM_BUILD_ROOT$ install

install -d $RPM_BUILD_ROOT%{_applnkdir}/Graphics/Viewers
mv $RPM_BUILD_ROOT%{_applnkdir}/Graphics{,/Viewers}/kghostview.desktop

%find_lang kdvi --with-kde
%find_lang kfract --with-kde
%find_lang kghostview --with-kde
%find_lang kiconedit --with-kde
%find_lang kpaint --with-kde
%find_lang kruler --with-kde
%find_lang ksnapshot --with-kde
%find_lang kview --with-kde

%post devel -p /sbin/ldconfig
%postun devel -p /sbin/ldconfig

%post kdvi -p /sbin/ldconfig
%postun kdvi -p /sbin/ldconfig

%post kfax -p /sbin/ldconfig
%postun kfax -p /sbin/ldconfig

%post kghostview -p /sbin/ldconfig
%postun kghostview -p /sbin/ldconfig

%post kview -p /sbin/ldconfig
%postun kview -p /sbin/ldconfig

%post kooka -p /sbin/ldconfig
%postun kooka -p /sbin/ldconfig

%post kcoloredit -p /sbin/ldconfig
%postun kcoloredit -p /sbin/ldconfig

%post kcolorchooser -p /sbin/ldconfig
%postun kcolorchooser -p /sbin/ldconfig

%clean
rm -rf $RPM_BUILD_ROOT

%files devel
%defattr(644,root,root,755)
%{_includedir}/*.h
%attr(755,root,root) %{_libdir}/libkscan.so

#################################################
#             KDVI
#################################################
%files kdvi -f kdvi.lang
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kdvi
%attr(755,root,root) %{_libdir}/libkdvi.??
%{_datadir}/apps/kdvi/
%{_applnkdir}/Graphics/kdvi.desktop
%{_pixmapsdir}/*/*/apps/kdvi.*

#################################################
#             KFAX
#################################################
%files kfax 
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kfax
%attr(755,root,root) %{_libdir}/libkfax.??
%{_datadir}/apps/kfax/
%{_applnkdir}/Graphics/kfax.desktop
%{_pixmapsdir}/*/*/apps/kfax.*

#################################################
#             KFRACT
#################################################
%files kfract -f kfract.lang
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kfract
%{_datadir}/apps/kfract/
%{_applnkdir}/Graphics/kfract.desktop
%{_pixmapsdir}/*/*/apps/kfract.*

#################################################
#             KGHOSTVIEW
#################################################
%files kghostview -f kghostview.lang
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kghostview
%attr(755,root,root) %{_libdir}/libkghostview.*
%{_datadir}/apps/kghostview
%{_applnkdir}/Graphics/Viewers/kghostview.desktop
%{_pixmapsdir}/*/*/apps/kghostview.*

#################################################
#             KICONEDIT
#################################################
%files kiconedit -f kiconedit.lang
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kiconedit
%{_datadir}/apps/kiconedit
%{_applnkdir}/Graphics/kiconedit.desktop
%{_pixmapsdir}/*/*/apps/kiconedit.*

#################################################
#             KPAINT
#################################################
%files kpaint -f kpaint.lang
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kpaint
%{_datadir}/apps/kpaint
%{_applnkdir}/Graphics/kpaint.desktop
%{_pixmapsdir}/*/*/apps/kpaint.*

#################################################
#             KRULER
#################################################
%files kruler -f kruler.lang
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kruler
%{_datadir}/apps/kruler
%{_applnkdir}/Graphics/kruler.desktop
%{_pixmapsdir}/*/*/apps/kruler.*

#################################################
#             KSNAPSHOT
#################################################
%files ksnapshot -f ksnapshot.lang
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/ksnapshot
%{_applnkdir}/Graphics/ksnapshot.desktop
%{_pixmapsdir}/*/*/apps/ksnapshot.*

#################################################
#             KVIEW
#################################################
%files kview -f kview.lang
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kview
%attr(755,root,root) %{_bindir}/kviewshell
%attr(755,root,root) %{_libdir}/kview.??
%attr(755,root,root) %{_libdir}/libkviewpart.??
%attr(755,root,root) %{_libdir}/libkviewerpart.??
%attr(755,root,root) %{_libdir}/libkmultipage.*
%attr(755,root,root) %{_libdir}/libkpagetest.??
%{_datadir}/apps/kview*
%{_applnkdir}/Graphics/kview.desktop
%{_pixmapsdir}/*/*/apps/kview.*

#################################################
#             KOOKA
#################################################
%files kooka
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kooka
%attr(755,root,root) %{_libdir}/libkscan.so.*.*.*
%attr(755,root,root) %{_libdir}/libkscan.la
%{_datadir}/apps/kooka
%{_datadir}/services/scanservice.desktop
%{_applnkdir}/Utilities/kooka.desktop
%{_pixmapsdir}/*/*/actions/palette*

#################################################
#             KCOLOREDIT
#################################################
%files kcoloredit
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kcoloredit
%{_applnkdir}/Graphics/kcoloredit.desktop
%{_pixmapsdir}/*/*/apps/kcoloredit.*

#################################################
#             KCOLORCHOOSER
#################################################
%files kcolorchooser
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/kcolorchooser
%attr(755,root,root) %{_libdir}/kcolorchooser.??
%{_applnkdir}/Graphics/kcolorchooser.desktop
